import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Disclaimer — RugSol",
  description: "Important disclaimers about using RugSol token security analysis.",
};

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen premium-bg text-text-primary">
      <Navbar />

      <main className="pt-20 md:pt-28 pb-20">
        <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
          {/* Header */}
          <div className="mb-12">
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-[var(--silver-accent)]/10 border border-[var(--silver-accent)]/30 mb-6 backdrop-blur-sm">
              <span className="text-sm font-medium silver-accent tracking-wide">Legal</span>
            </div>
            <h1 className="text-3xl sm:text-4xl font-bold tracking-tight mb-4">
              Disclaimer
            </h1>
            <p className="text-sm text-text-muted">
              Last updated: February 1, 2026
            </p>
          </div>

          {/* Main Warning */}
          <div className="glass-card p-6 rounded-2xl border border-amber-500/20 bg-amber-500/5 mb-8">
            <div className="flex items-start gap-4">
              <div className="w-10 h-10 rounded-xl bg-amber-500/10 flex items-center justify-center shrink-0">
                <svg className="w-5 h-5 text-amber-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z" />
                </svg>
              </div>
              <div>
                <h2 className="text-base font-semibold text-text-primary mb-2">Important Notice</h2>
                <p className="text-sm text-text-secondary leading-relaxed">
                  RugSol is an informational tool only. It does <strong className="text-text-primary">not</strong> provide
                  financial advice, investment recommendations, or guarantees of any kind. Cryptocurrency
                  trading involves substantial risk of loss. Always do your own research (DYOR) before
                  making any trading or investment decisions.
                </p>
              </div>
            </div>
          </div>

          {/* Sections */}
          <div className="space-y-6">
            <div className="glass-card p-6 rounded-2xl">
              <h2 className="text-base font-semibold text-text-primary mb-3">
                No Guarantee of Accuracy
              </h2>
              <p className="text-sm text-text-secondary leading-relaxed">
                Risk scores, letter grades, and security assessments are generated by automated algorithms
                analyzing publicly available on-chain data. These results represent a point-in-time analysis
                and may not reflect the current state of a token. A high score (A or B grade) does not mean
                a token is safe to invest in. A low score (D or F grade) does not constitute a definitive
                determination that a token is a scam. Token conditions can change rapidly after analysis.
              </p>
            </div>

            <div className="glass-card p-6 rounded-2xl">
              <h2 className="text-base font-semibold text-text-primary mb-3">
                Limitations of Automated Analysis
              </h2>
              <p className="text-sm text-text-secondary leading-relaxed">
                Our analysis covers common rug pull vectors including mint/freeze authority abuse, holder
                concentration, liquidity manipulation, and honeypot mechanisms. However, new attack vectors
                and sophisticated scams may not be detected. Social engineering, off-chain fraud, team
                abandonment, and market manipulation are examples of risks that cannot be fully assessed
                through on-chain analysis alone.
              </p>
            </div>

            <div className="glass-card p-6 rounded-2xl">
              <h2 className="text-base font-semibold text-text-primary mb-3">
                Third-Party Data
              </h2>
              <p className="text-sm text-text-secondary leading-relaxed">
                RugSol relies on data from third-party providers including blockchain RPC nodes, price
                aggregators, and DEX APIs. We do not control the accuracy, completeness, or availability
                of this data. Service interruptions from third-party providers may result in incomplete
                or unavailable scan results.
              </p>
            </div>

            <div className="glass-card p-6 rounded-2xl">
              <h2 className="text-base font-semibold text-text-primary mb-3">
                Assumption of Risk
              </h2>
              <p className="text-sm text-text-secondary leading-relaxed">
                By using RugSol, you acknowledge and accept that: (a) cryptocurrency trading is inherently
                risky; (b) you may lose some or all of your invested capital; (c) past security scores
                do not predict future token behavior; (d) you are solely responsible for your own trading
                decisions; (e) RugSol bears no liability for any financial losses incurred.
              </p>
            </div>

            <div className="glass-card p-6 rounded-2xl">
              <h2 className="text-base font-semibold text-text-primary mb-3">
                Not an Endorsement
              </h2>
              <p className="text-sm text-text-secondary leading-relaxed">
                The appearance of any token on the RugSol platform does not constitute an endorsement,
                recommendation, or certification. We analyze tokens submitted by users and do not curate,
                promote, or recommend any specific token or project.
              </p>
            </div>
          </div>

          {/* CTA */}
          <div className="mt-12 text-center">
            <p className="text-sm text-text-muted mb-4">
              By continuing to use RugSol, you acknowledge that you have read and understood this disclaimer.
            </p>
            <Link
              href="/"
              className="btn-premium inline-flex items-center gap-2 px-6 py-3 rounded-xl text-sm font-medium"
            >
              Back to Scanner
            </Link>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
